// Code generated by go-swagger; DO NOT EDIT.

package hello_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/sdinsure/agent/example/api/go-openapiv2/models"
)

// HelloServiceSayHelloStreamReader is a Reader for the HelloServiceSayHelloStream structure.
type HelloServiceSayHelloStreamReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HelloServiceSayHelloStreamReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHelloServiceSayHelloStreamOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewHelloServiceSayHelloStreamDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewHelloServiceSayHelloStreamOK creates a HelloServiceSayHelloStreamOK with default headers values
func NewHelloServiceSayHelloStreamOK() *HelloServiceSayHelloStreamOK {
	return &HelloServiceSayHelloStreamOK{}
}

/*
HelloServiceSayHelloStreamOK describes a response with status code 200, with default header values.

A successful response.(streaming responses)
*/
type HelloServiceSayHelloStreamOK struct {
	Payload *HelloServiceSayHelloStreamOKBody
}

// IsSuccess returns true when this hello service say hello stream o k response has a 2xx status code
func (o *HelloServiceSayHelloStreamOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this hello service say hello stream o k response has a 3xx status code
func (o *HelloServiceSayHelloStreamOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this hello service say hello stream o k response has a 4xx status code
func (o *HelloServiceSayHelloStreamOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this hello service say hello stream o k response has a 5xx status code
func (o *HelloServiceSayHelloStreamOK) IsServerError() bool {
	return false
}

// IsCode returns true when this hello service say hello stream o k response a status code equal to that given
func (o *HelloServiceSayHelloStreamOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the hello service say hello stream o k response
func (o *HelloServiceSayHelloStreamOK) Code() int {
	return 200
}

func (o *HelloServiceSayHelloStreamOK) Error() string {
	return fmt.Sprintf("[GET /v1/hello:stream][%d] helloServiceSayHelloStreamOK  %+v", 200, o.Payload)
}

func (o *HelloServiceSayHelloStreamOK) String() string {
	return fmt.Sprintf("[GET /v1/hello:stream][%d] helloServiceSayHelloStreamOK  %+v", 200, o.Payload)
}

func (o *HelloServiceSayHelloStreamOK) GetPayload() *HelloServiceSayHelloStreamOKBody {
	return o.Payload
}

func (o *HelloServiceSayHelloStreamOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(HelloServiceSayHelloStreamOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHelloServiceSayHelloStreamDefault creates a HelloServiceSayHelloStreamDefault with default headers values
func NewHelloServiceSayHelloStreamDefault(code int) *HelloServiceSayHelloStreamDefault {
	return &HelloServiceSayHelloStreamDefault{
		_statusCode: code,
	}
}

/*
HelloServiceSayHelloStreamDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type HelloServiceSayHelloStreamDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this hello service say hello stream default response has a 2xx status code
func (o *HelloServiceSayHelloStreamDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this hello service say hello stream default response has a 3xx status code
func (o *HelloServiceSayHelloStreamDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this hello service say hello stream default response has a 4xx status code
func (o *HelloServiceSayHelloStreamDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this hello service say hello stream default response has a 5xx status code
func (o *HelloServiceSayHelloStreamDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this hello service say hello stream default response a status code equal to that given
func (o *HelloServiceSayHelloStreamDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the hello service say hello stream default response
func (o *HelloServiceSayHelloStreamDefault) Code() int {
	return o._statusCode
}

func (o *HelloServiceSayHelloStreamDefault) Error() string {
	return fmt.Sprintf("[GET /v1/hello:stream][%d] HelloService_SayHelloStream default  %+v", o._statusCode, o.Payload)
}

func (o *HelloServiceSayHelloStreamDefault) String() string {
	return fmt.Sprintf("[GET /v1/hello:stream][%d] HelloService_SayHelloStream default  %+v", o._statusCode, o.Payload)
}

func (o *HelloServiceSayHelloStreamDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *HelloServiceSayHelloStreamDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
HelloServiceSayHelloStreamOKBody Stream result of apiHelloResponse
swagger:model HelloServiceSayHelloStreamOKBody
*/
type HelloServiceSayHelloStreamOKBody struct {

	// error
	Error *models.RPCStatus `json:"error,omitempty"`

	// result
	Result *models.APIHelloResponse `json:"result,omitempty"`
}

// Validate validates this hello service say hello stream o k body
func (o *HelloServiceSayHelloStreamOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *HelloServiceSayHelloStreamOKBody) validateError(formats strfmt.Registry) error {
	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("helloServiceSayHelloStreamOK" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("helloServiceSayHelloStreamOK" + "." + "error")
			}
			return err
		}
	}

	return nil
}

func (o *HelloServiceSayHelloStreamOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("helloServiceSayHelloStreamOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("helloServiceSayHelloStreamOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this hello service say hello stream o k body based on the context it is used
func (o *HelloServiceSayHelloStreamOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *HelloServiceSayHelloStreamOKBody) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if o.Error != nil {

		if swag.IsZero(o.Error) { // not required
			return nil
		}

		if err := o.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("helloServiceSayHelloStreamOK" + "." + "error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("helloServiceSayHelloStreamOK" + "." + "error")
			}
			return err
		}
	}

	return nil
}

func (o *HelloServiceSayHelloStreamOKBody) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if o.Result != nil {

		if swag.IsZero(o.Result) { // not required
			return nil
		}

		if err := o.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("helloServiceSayHelloStreamOK" + "." + "result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("helloServiceSayHelloStreamOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *HelloServiceSayHelloStreamOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *HelloServiceSayHelloStreamOKBody) UnmarshalBinary(b []byte) error {
	var res HelloServiceSayHelloStreamOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
