// Code generated by go-swagger; DO NOT EDIT.

package hello_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHelloServiceSayHelloStreamParams creates a new HelloServiceSayHelloStreamParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHelloServiceSayHelloStreamParams() *HelloServiceSayHelloStreamParams {
	return &HelloServiceSayHelloStreamParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHelloServiceSayHelloStreamParamsWithTimeout creates a new HelloServiceSayHelloStreamParams object
// with the ability to set a timeout on a request.
func NewHelloServiceSayHelloStreamParamsWithTimeout(timeout time.Duration) *HelloServiceSayHelloStreamParams {
	return &HelloServiceSayHelloStreamParams{
		timeout: timeout,
	}
}

// NewHelloServiceSayHelloStreamParamsWithContext creates a new HelloServiceSayHelloStreamParams object
// with the ability to set a context for a request.
func NewHelloServiceSayHelloStreamParamsWithContext(ctx context.Context) *HelloServiceSayHelloStreamParams {
	return &HelloServiceSayHelloStreamParams{
		Context: ctx,
	}
}

// NewHelloServiceSayHelloStreamParamsWithHTTPClient creates a new HelloServiceSayHelloStreamParams object
// with the ability to set a custom HTTPClient for a request.
func NewHelloServiceSayHelloStreamParamsWithHTTPClient(client *http.Client) *HelloServiceSayHelloStreamParams {
	return &HelloServiceSayHelloStreamParams{
		HTTPClient: client,
	}
}

/*
HelloServiceSayHelloStreamParams contains all the parameters to send to the API endpoint

	for the hello service say hello stream operation.

	Typically these are written to a http.Request.
*/
type HelloServiceSayHelloStreamParams struct {

	// Greeting.
	Greeting *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the hello service say hello stream params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HelloServiceSayHelloStreamParams) WithDefaults() *HelloServiceSayHelloStreamParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the hello service say hello stream params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HelloServiceSayHelloStreamParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the hello service say hello stream params
func (o *HelloServiceSayHelloStreamParams) WithTimeout(timeout time.Duration) *HelloServiceSayHelloStreamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the hello service say hello stream params
func (o *HelloServiceSayHelloStreamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the hello service say hello stream params
func (o *HelloServiceSayHelloStreamParams) WithContext(ctx context.Context) *HelloServiceSayHelloStreamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the hello service say hello stream params
func (o *HelloServiceSayHelloStreamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the hello service say hello stream params
func (o *HelloServiceSayHelloStreamParams) WithHTTPClient(client *http.Client) *HelloServiceSayHelloStreamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the hello service say hello stream params
func (o *HelloServiceSayHelloStreamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGreeting adds the greeting to the hello service say hello stream params
func (o *HelloServiceSayHelloStreamParams) WithGreeting(greeting *string) *HelloServiceSayHelloStreamParams {
	o.SetGreeting(greeting)
	return o
}

// SetGreeting adds the greeting to the hello service say hello stream params
func (o *HelloServiceSayHelloStreamParams) SetGreeting(greeting *string) {
	o.Greeting = greeting
}

// WriteToRequest writes these params to a swagger request
func (o *HelloServiceSayHelloStreamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Greeting != nil {

		// query param greeting
		var qrGreeting string

		if o.Greeting != nil {
			qrGreeting = *o.Greeting
		}
		qGreeting := qrGreeting
		if qGreeting != "" {

			if err := r.SetQueryParam("greeting", qGreeting); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
