// Code generated by go-swagger; DO NOT EDIT.

package hello_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new hello service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for hello service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	HelloServiceSayHello(params *HelloServiceSayHelloParams, opts ...ClientOption) (*HelloServiceSayHelloOK, error)

	HelloServiceSayHelloStream(params *HelloServiceSayHelloStreamParams, opts ...ClientOption) (*HelloServiceSayHelloStreamOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
HelloServiceSayHello hello service say hello API
*/
func (a *Client) HelloServiceSayHello(params *HelloServiceSayHelloParams, opts ...ClientOption) (*HelloServiceSayHelloOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHelloServiceSayHelloParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "HelloService_SayHello",
		Method:             "GET",
		PathPattern:        "/v1/hello",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &HelloServiceSayHelloReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*HelloServiceSayHelloOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*HelloServiceSayHelloDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
HelloServiceSayHelloStream hello service say hello stream API
*/
func (a *Client) HelloServiceSayHelloStream(params *HelloServiceSayHelloStreamParams, opts ...ClientOption) (*HelloServiceSayHelloStreamOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHelloServiceSayHelloStreamParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "HelloService_SayHelloStream",
		Method:             "GET",
		PathPattern:        "/v1/hello:stream",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &HelloServiceSayHelloStreamReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*HelloServiceSayHelloStreamOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*HelloServiceSayHelloStreamDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
