// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIHelloResponse api hello response
//
// swagger:model apiHelloResponse
type APIHelloResponse struct {

	// reply
	Reply string `json:"reply,omitempty"`
}

// Validate validates this api hello response
func (m *APIHelloResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api hello response based on context it is used
func (m *APIHelloResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIHelloResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIHelloResponse) UnmarshalBinary(b []byte) error {
	var res APIHelloResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
